# Generated by Django 3.1.4 on 2021-08-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_abtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='model_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='mlalgorithm',
            name='model_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
